use_frameworks!

target 'CoreDataTableViewController_Example' do
  pod 'CoreDataTableViewController', :path => '../'

  target 'CoreDataTableViewController_Tests' do
    inherit! :search_paths

    
  end
end
